version: "2.1"
services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio-docker-local-storage-vol
    ports:
      - "4873:4873"
    volumes:
      - verdaccio:/verdaccio/storage:z
      - ./conf:/verdaccio/conf:z
volumes:
  verdaccio:
    driver: local
